stages:
  download_data:
    cmd: python -m gan_busters.data_pipeline.download
    deps:
      - gan_busters/data_pipeline/download.py
    outs:
      - data/raw:
          cache: false

  inspect_data:
    cmd: python -m gan_busters.data_pipeline.inspect
    deps:
      - data/raw
      - gan_busters/data_pipeline/inspect.py
      - gan_busters/config.py
    outs:
      - data/interim

  data_integrity:
    cmd: python -m gan_busters.data_pipeline.data_integrity
    deps:
      - data/interim/inspected_records.csv
      - gan_busters/data_pipeline/data_integrity.py
      - gan_busters/config.py
    outs:
      - data/processed